language_codes = {
    "Arabic": "ar",
    "Chinese (Simplified)": "zh",
    "Chinese (Traditional)": "zh-TW",
    "Danish": "da",
    "Dutch": "nl",
    "English": "en",
    "Filipino": "tl",
    "French": "fr",
    "German": "de",
    "Hindi": "hi",
    "Italian": "it",
    "Japanese": "ja",
    "Korean": "ko",
    "Norwegian": "no",
    "Polish": "pl",
    "Portuguese": "pt",
    "Romanian": "ro",
    "Russian": "ru",
    "Spanish": "es",
    "Swedish": "sv",
    "Turkish": "tr",
    "Welsh": "cy",
}

language_codes_polly = {
    "Arabic (Male)": "Zayd",
    "Arabic (Female)": "Hala",
    "Chinese (Mandarin, Female)": "Zhiyu",
    "Danish (Female)": "Sofie",
    "Dutch (Female)": "Laura",
    "English (Australian, Female)": "Olivia",
    "English (British, Male)": "Brian",
    "English (British, Female)": "Amy",
    "English (Indian, Female)": "Kajal",
    "English (US, Male)": "Joey",
    "English (US, Female)": "Salli",
    "French (Canadian, Male)": "Liam",
    "French (Canadian, Female)": "Gabrielle",
    "French (Female)": "Léa",
    "French (Male)": "Rémi",
    "German (Female)": "Vicki",
    "German (Male)": "Daniel",
    "Hindi (Female)": "Kajal",
    "Italian (Female)": "Bianca",
    "Italian (Male)": "Adriano",
    "Japanese (Female)": "Tomoko",
    "Japanese (Male)": "Takumi",
    "Korean (Female)": "Seoyeon",
    "Norwegian (Female)": "Ida",
    "Polish (Female)": "Ola",
    "Portuguese (Brazilian, Female)": "Camila",
    "Portuguese (Brazilian, Male)": "Thiago",
    "Portuguese (European, Female)": "Ines",
    "Spanish (European, Female)": "Lucia",
    "Spanish (European, Male)": "Sergio",
    "Spanish (Mexican, Female)": "Mia",
    "Spanish (Mexican, Male)": "Andrés",
    "Spanish (US, Female)": "Lupe",
    "Spanish (US, Male)": "Pedro",
    "Swedish (Female)": "Elin",
    "Turkish (Female)": "Burcu",
}

merged_languages_with_voices = {
    "English": ["English (Australian, Female)", "English (British, Male)", "English (British, Female)", "English (Indian, Female)", "English (US, Male)", "English (US, Female)"],
    "French": ["French (Canadian, Male)", "French (Canadian, Female)", "French (Female)", "French (Male)"],
    "Portuguese": ["Portuguese (Brazilian, Female)", "Portuguese (Brazilian, Male)", "Portuguese (European, Female)"],
    "Spanish": ["Spanish (European, Female)", "Spanish (European, Male)", "Spanish (Mexican, Female)", "Spanish (Mexican, Male)", "Spanish (US, Female)", "Spanish (US, Male)"],
    "Arabic": ["Arabic (Male)", "Arabic (Female)"],
    "Chinese (Traditional)": ["Chinese (Mandarin, Female)"],
    "Chinese (Simplified)": ["Chinese (Mandarin, Female)"],
    "Danish": ["Danish (Female)"],
    "Dutch": ["Dutch (Female)"],
    "German": ["German (Female)", "German (Male)"],
    "Hindi": ["Hindi (Female)"],
    "Italian": ["Italian (Female)", "Italian (Male)"],
    "Japanese": ["Japanese (Female)", "Japanese (Male)"],
    "Korean": ["Korean (Female)"],
    "Norwegian": ["Norwegian (Female)"],
    "Polish": ["Polish (Female)"],
    "Romanian": ["Romanian (Female)"],
    "Swedish": ["Swedish (Female)"],
    "Turkish": ["Turkish (Female)"]
}

languages = [
    "Arabic",
    "Chinese (Simplified)",
    "Chinese (Traditional)",
    "Danish",
    "Dutch",
    "English",
    "French",
    "German",
    "Hindi",
    "Italian",
    "Japanese",
    "Korean",
    "Norwegian",
    "Polish",
    "Portuguese",
    "Spanish",
    "Swedish",
    "Turkish",
]
